/*
Write a program that input a two digit positive integer and allows the user to perform one or more of the following operations:

1.doubleNum: Double the number.

2.reverseDigit: Reverse the digits of the number.

3.raisePow2_3_4: Raise the number to the power of 2, 3, or 4.

4.sumDigits: Sum the digits of the number.

5.raiseFirstDigitPowSecondDigit: If the number is a two-digit number, then raise the first digit to the power of the second digit.

6.raiseFirstAndSecondDigitPowThirdDigit: If the number is a three-digit number and the last digit is less than or equal to 4, then raise the first two digits to the power of the last digit.

After performing an operation if the number is less than 10, add 10 to the number. 

Each successive operation should be performed on the number generated by the last operation. Your program should not contain any global variables and each of these operations must be implemented by a separate function.



Note that only upload functions

For example:

Test
int num;
int choice;
int exponent;

cin >> num;
while(cin >> choice, choice){
    switch(choice)
    {
    case 1:
        num = doubleNum(num);
        break;
    case 2:
        num = reverseDigit(num);
        break;
    case 3:
        cin >> exponent;
        num = raisePow2_3_4(num, exponent);
        break;
    case 4:
        num = sumDigits(num);
        break;
    case 5:
        num = raiseFirstDigitPowSecondDigit(num);
        break;
    case 6:
        num = raiseFirstAndSecondDigitPowThirdDigit(num);
        break;
    }
    cout << num << endl;
}

Input
15
1
2
3 2
3 4
2
4
5
5
1
3 2
4
3 2
6
0

Result	
30
13
169
815730721
127037518
34
81
18
36
1296
18
324
1048576
*/

int doubleNum(int num){
  num=num*2;
  if(num<10)
  num=num+10;
  return num;
}

int reverseDigit(int num){
  int a = num;
  int n=0;
  while(a!=0){
    n++;
    a=a/10;
  }
  int m=n;
  for(int i=n;i>0;i--){
    m=1;
    for(int j=1;j<i;j++){
        m = m * 10;
    }
    a = num%10*m+a;
    num=num/10;
  }
  if(a<10)
    a=a+10;
  return a;
}

int raisePow2_3_4(int num, int exponent){
  int a = num;
  for(int i=1;i<exponent;i++){
    num = num*a;
  }
  if(num<10)
    num=num+10;
  return num;
}

int sumDigits(int num){
  int a = num;
  int n=0;
  while(a!=0){
    n++;
    a=a/10;
  }
  for(int i=n;i>0;i--){
    a = num%10+a;
    num=num/10;
  }
  if(a<10)
    a=a+10;
  return a;
}

int raiseFirstDigitPowSecondDigit(int num){
    int a = num%10;
    int b = num/10;
    int c = raisePow2_3_4(b, a);
    if(c<10)
      c=c+10;
    return c;
}

int raiseFirstAndSecondDigitPowThirdDigit(int num){
    int a = num%10;
    int b = num/10;
    if(a<=4)
        return raisePow2_3_4(b, a);
    else
        return num;
}